-- PostgreSQL baseline for a NEW schema. Apply once; do not run against existing tables.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6), updated_at TIMESTAMP(6),
    user_name VARCHAR(255) UNIQUE, full_name VARCHAR(255)
);
CREATE TABLE venue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6), updated_at TIMESTAMP(6)
);
CREATE TABLE show_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6), updated_at TIMESTAMP(6),
    active BOOLEAN, title VARCHAR(255), description VARCHAR(255)
);
CREATE TABLE seat_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6), updated_at TIMESTAMP(6),
    venue_id BIGINT NOT NULL REFERENCES venue(id), enabled BOOLEAN,
    row_no VARCHAR(255), column_no VARCHAR(255),
    label VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL,
    price NUMERIC(12,2) NOT NULL CHECK (price >= 0)
);
CREATE TABLE show_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6), updated_at TIMESTAMP(6),
    show_id BIGINT NOT NULL REFERENCES show_details(id),
    venue_id BIGINT NOT NULL REFERENCES venue(id),
    starts_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    active BOOLEAN NOT NULL,
    CHECK (ends_at > starts_at)
);
CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6), updated_at TIMESTAMP(6),
    user_id BIGINT NOT NULL REFERENCES users(id),
    show_schedule_id BIGINT NOT NULL REFERENCES show_schedule(id),
    status VARCHAR(255) NOT NULL CHECK (status IN
        ('IN_PROGRESS', 'CONFIRMED', 'EXPIRED', 'RELEASED', 'CANCELLED')),
    start_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    total NUMERIC(12,2) NOT NULL CHECK (total >= 0),
    currency VARCHAR(3) NOT NULL,
    CHECK (expires_at > start_at)
);
CREATE INDEX idx_booking_customer ON bookings(user_id);
CREATE INDEX idx_booking_schedule_status ON bookings(show_schedule_id, status, expires_at);
CREATE TABLE booking_seats (
    booking_id BIGINT NOT NULL REFERENCES bookings(id),
    seat_id BIGINT NOT NULL REFERENCES seat_details(id),
    label VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL,
    price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
    PRIMARY KEY (booking_id, seat_id)
);
CREATE INDEX idx_booking_seats_seat ON booking_seats(seat_id, booking_id);
