-- Apply after V1. Preserve existing seat snapshots while adding entity identity.
ALTER TABLE booking_seats
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN created_at TIMESTAMP(6),
    ADD COLUMN updated_at TIMESTAMP(6);

UPDATE booking_seats seat
SET created_at = booking.created_at, updated_at = booking.updated_at
FROM bookings booking
WHERE booking.id = seat.booking_id;

ALTER TABLE booking_seats DROP CONSTRAINT booking_seats_pkey;
ALTER TABLE booking_seats ADD CONSTRAINT booking_seats_pkey PRIMARY KEY (id);
ALTER TABLE booking_seats ADD CONSTRAINT uk_booking_seats_booking_seat
    UNIQUE (booking_id, seat_id);
