-- Apply once after V1 and V2; no external calls are performed by this migration.
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6), updated_at TIMESTAMP(6),
    booking_id BIGINT NOT NULL UNIQUE REFERENCES bookings(id),
    amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    currency VARCHAR(3) NOT NULL,
    pay_mode VARCHAR(255) NOT NULL CHECK (pay_mode = 'UPI'),
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED')),
    provider_payment_id VARCHAR(255),
    CHECK (status <> 'SUCCEEDED' OR provider_payment_id IS NOT NULL)
);
CREATE TABLE payment_refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6), updated_at TIMESTAMP(6),
    payment_id BIGINT NOT NULL UNIQUE REFERENCES payments(id),
    booking_id BIGINT NOT NULL REFERENCES bookings(id),
    amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED')),
    provider_refund_id VARCHAR(255)
);
CREATE TABLE payment_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6), updated_at TIMESTAMP(6),
    booking_id BIGINT NOT NULL REFERENCES bookings(id),
    payment_id BIGINT NOT NULL REFERENCES payments(id),
    type VARCHAR(255) NOT NULL CHECK (type IN ('PAYMENT', 'REFUND')),
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'PROCESSING', 'DONE')),
    hold_expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    next_attempt_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    lease_until TIMESTAMP(6) WITH TIME ZONE,
    claim_token UUID,
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    correlation_id VARCHAR(255) NOT NULL,
    UNIQUE (payment_id, type),
    CHECK ((status = 'PROCESSING' AND claim_token IS NOT NULL AND lease_until IS NOT NULL)
        OR (status <> 'PROCESSING' AND claim_token IS NULL AND lease_until IS NULL))
);
CREATE INDEX idx_outbox_pending ON payment_outbox(next_attempt_at, id) WHERE status = 'PENDING';
CREATE INDEX idx_outbox_leases ON payment_outbox(lease_until, id) WHERE status = 'PROCESSING';
